# Generated by Django 4.1.13 on 2025-04-26 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('type', models.CharField(max_length=50)),
                ('difficuilty', models.CharField(max_length=10)),
                ('statement', models.TextField()),
                ('task', models.TextField(null=True)),
                ('time_complexity', models.CharField(max_length=50, null=True)),
                ('space_complexity', models.CharField(max_length=50, null=True)),
                ('constraints', models.JSONField(default=list, null=True)),
                ('example', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=122, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('problems_solved', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.problem')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_sample', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='Home.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(null=True)),
                ('verdict', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python_solution', models.TextField(blank=True, null=True)),
                ('cpp_solution', models.TextField(blank=True, null=True)),
                ('java_solution', models.TextField(blank=True, null=True)),
                ('function_name', models.CharField(max_length=100)),
                ('python_template', models.TextField(blank=True, null=True)),
                ('cpp_template', models.TextField(blank=True, null=True)),
                ('java_template', models.TextField(blank=True, null=True)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='Home.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contests', to='Home.user')),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_contests', to='Home.user')),
                ('problems', models.ManyToManyField(related_name='contests', to='Home.problem')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
