# Generated by Django 4.1.13 on 2025-04-26 11:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='constraints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficuilty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.CharField(choices=[('Array', 'Array'), ('String', 'String'), ('Tree', 'Tree'), ('Graph', 'Graph'), ('Dynamic Programming', 'Dynamic Programming'), ('Greedy', 'Greedy'), ('Backtracking', 'Backtracking'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='problemsolution',
            name='function_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Function name must be a valid identifier', regex='^[a-zA-Z_][a-zA-Z0-9_]*$')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error'), ('PE', 'Presentation Error')], max_length=255),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases_set', to='Home.problem'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=122, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=122, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(122), django.core.validators.RegexValidator(message='Username can only contain letters, numbers, and underscores', regex='^[a-zA-Z0-9_]+$')]),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('submission', 'Submission'), ('achievement', 'Achievement'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='Home.user')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-time'],
            },
        ),
    ]
