# Generated by Django 4.1.13 on 2025-04-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_problem_constraints_alter_problem_difficuilty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='constraints',
            field=models.TextField(blank=True, help_text='Enter each constraint on a new line', null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='space_complexity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_complexity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
