# Generated by Django 4.1.13 on 2025-04-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_problem_constraints_alter_problem_example_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='task',
            field=models.TextField(blank=True, null=True),
        ),
    ]
